### ISSUE TITLE
Add filter to tell messages

### ISSUE THREAD

**Issue by majovec** [survanetwork/BadWordBlocker#1]
This plugin is block word on /tell ?

**Comment by jarne** [comment]
It isn't able to block private messages yet. To do this, the plugin would need to override the tell command and this would cause incompatibility to other plugins (which maybe also override the tell command).

**Comment by jarne** [comment]
Maybe I could try recognizing filtered words on CommandPreprocessEvent, I'll take a look at this soon.

**Comment by jarne** [comment]
Added with 4a0a30c1f778e23f8094baef15497368b2c132ed, thanks for the suggestion!
