### ISSUE TITLE
Add an option to kick/ban spammers

### ISSUE THREAD

**Issue by teracube** [survanetwork/BadWordBlocker#10]
1/ could you please add prevent spam repetitive sentence
2/could you please add an action to kick/ban spammer on config.yml

sorry for my bad english
thanks

**Comment by jarne** [comment]
Your first point is already possible with this plugin, you can't send the same chat message twice. I'll add your second point to the feature requests list.

**Comment by jarne** [comment]
Thanks for your feature request, a configurable kick/ban option has been added in the latest version!
