### ISSUE TITLE
Request: Notify User, which word is being blocked.

### ISSUE THREAD

**Issue by ver24436** [survanetwork/BadWordBlocker#15]
One thing, I feel could improve this plugin, is when a word is blocked, have it relay that to the user. 

Often there are a number of false positives, which can make it difficult to determine which word is tripping it up. This small change could help limit the frustration of players having to retype a message multiple times trying to figure out which word it's unhappy with.

**Comment by jarne** [comment]
Thanks for your request, has been added to the latest version as an option to the config (off by default) 👍
